### ISSUE TITLE
armv6 support

### ISSUE THREAD

**Issue by hassiweb** [geerlingguy/ansible-role-docker_arm#21]
Hi,
Are there any reasons why armv6 (for Raspberry Pi Zero) is not supported?
If not, may I make a pull request?

p.s. I'm a fan of your YouTube!!  Thanks for the great info!!

**Comment by geerlingguy** [comment]
If you can find a simple way to make sure it works I'd be willing to merge. I just haven't had as much luck trying to get useful things running in Docker on the Zero.

**Comment by geerlingguy** [comment]
Merged; I'll tag a new release shortly. Thanks!

**Comment by hassiweb** [comment]
Thx for the quick response!!
