### ISSUE TITLE
Unable to uninstall docker

### ISSUE THREAD

**Issue by FrankGiesecke** [geerlingguy/ansible-role-docker_arm#31]
I usually use your `docker` role to install/uninstall docker in systems.

Since I have to manage some raspberry systems, I also use your `docker_arm` role.

Today, I want to remove docker from one raspberry. So I configured the variable `docker_package_state` to "absent", like I do this on all other system. Now I must learn, that the `docker_arm` role doesn't support this.

It would be great, if the role also support removing docker on the same way the `docker` role does.

**Comment by geerlingguy** [comment]
I'd be open to a PR that adds that ability, though I probably won't work on it on my own for the time being.
